# Generated by Django 3.0.8 on 2020-07-31 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guild_bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='character',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='guild_bank.Character'),
        ),
    ]
