# Generated by Django 3.0.8 on 2020-08-23 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guild_bank', '0004_character_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guild_bank.Character'),
        ),
    ]
