# Generated by Django 3.0.8 on 2020-09-08 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guild_bank', '0006_item_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemcategory',
            options={'verbose_name_plural': 'item categories'},
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.IntegerField()),
                ('key', models.CharField(max_length=128)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guild_bank.Bank')),
            ],
        ),
    ]
