# Generated by Django 3.0.8 on 2020-09-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild_bank', '0007_webhook'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='money',
            field=models.IntegerField(default=0),
        ),
    ]
